# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Chapter'),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.IntegerField(default=-2),
        ),
    ]
